sonar.projectKey=linker-front
sonar.projectName=linker-front
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=squ_70902c83b995c14b8759ca93bf148e71151083b5

sonar.sources=src/app/features,src/app/shared
sonar.tests=src/app/features,src/app/shared

sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/assets/**,src/app/shared/services/logger.ts,**/*.css,**/*.html

sonar.coverage.exclusions=**/*.module.ts

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
sonar.sourceEncoding=UTF-8