sonar.projectKey=Linker-Frontend
sonar.projectName=Linker Frontend
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=squ_16c84e9f7e146938ff194f2ff6f12fa55665a5dc

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.inclusions=src/app/shared/components/header/**/*.ts,src/app/features/login/**/*.ts,src/app/features/perfil-postulante/**/*.ts,src/app/features/match/swipe/**/*.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/assets/**

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8                                                                                                                        
