sonar.projectKey=linker-front
sonar.projectName=linker-front
sonar.projectVersion=1.0
sonar.host.url=http://sonarqube-test:9000
sonar.token=squ_edc617e57d38b18ad0f8577512cc58d57567af1f
sonar.sources=src/app/features,src/app/shared/components/header
sonar.tests=src/app/features,src/app/shared/components/header
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/assets/**
sonar.coverage.exclusions=**/*.module.ts,**/services/**,**/*.css,**/*.html,**/hero/**
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info
sonar.sourceEncoding=UTF-8
sonar.projectBaseDir=.