sonar.projectKey=Linker-Backend
sonar.projectName=Linker Backend
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=squ_26370d66c32e9df3f26405ffc57a91243b3372cd
sonar.projectBaseDir=.

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8